added backup/restore feature

diff --git a/patch b/patch
--- a/patch
+++ b/patch
@@ -10,11 +10,12 @@ PATCHED_FILES_DIR="$SCRIPTROOT/files"
 MANIFEST_CONFIG="$SCRIPTROOT/manifest.cfg"
 MANIFEST="$SCRIPTROOT/manifest"
 PATCH_DIR="$SCRIPTROOT/patches"
+BACKUP_DIR="$SCRIPTROOT/backup"
 
 
 WriteManifestLine() {
 	dest=$1
-	echo "adding $dest to manifest"
+	#echo "adding $dest to manifest"
 	# Calculate hash
         md5=`md5sum $dest | cut -d ' ' -f 1`
 	# Copy dir structure and file to patched files
@@ -31,9 +32,20 @@ WriteManifestLine() {
 	if [ -z $md5 ]; then
 		md5="-"
 	fi
-
-	# Write data to manifest 
-	echo "$md5,$src,$dest,$owner,$group,$perms" >> $MANIFEST
+	touch $MANIFEST > /dev/null
+	
+	# Check if data is already in manifest
+	line="$md5,$src,$dest,$owner,$group,$perms"
+	if [ -f "$dest" ]; then
+		if ! grep -q "$dest" "$MANIFEST"
+	 	then
+			echo "adding $dest to manifest"
+			echo $line >> $MANIFEST
+		fi
+	else
+		echo "adding $dest to manifest"
+		echo $line >> $MANIFEST
+	fi
 }
 
 
@@ -41,6 +53,9 @@ WriteManifestLine() {
 # Contains MD5 hash, and src/dest file paths
 Build() {
 	echo "Building manifest..."
+
+	# Remove any pre-existing backups
+	rm -rf $BACKUP_DIR 2> /dev/null
 	
 	# Will store patched files
 	mkdir -p $PATCHED_FILES_DIR 2> /dev/null
@@ -86,11 +101,9 @@ ApplyPatches() {
 		exit 1
 	fi
 	
-	# Create a backup
-	Backup
-
 	num_patched=0
 	mkdir $PATCH_DIR	
+	
 	# Read each line in manifest
         while read -r line
 	do
@@ -109,6 +122,9 @@ ApplyPatches() {
 		elif [ -f $dest ]; then						
 			diff -u $dest $src > /dev/null				# check file diff
 			if [ $? -eq 1 ]; then					# return code 1 mean patch req'd
+				# Create a backup of this file
+				Backup $dest
+				
 				diff -u $dest $src > "$PATCH_DIR/file.patch"	# create patch file
 				patch -u $dest -i "$PATCH_DIR/file.patch"	# patch the file
 				((num_patched++))				# increment counter
@@ -117,13 +133,14 @@ ApplyPatches() {
 		else
 			# File is missingi from filesystem, replace it
 			mkdir -p `dirname $dest` # Create destination directories
-			cp -fpv $src $dest	 # Copy file from patch to filesystem
+			echo "installing $dest"
+			cp -fp $src $dest	 # Copy file from patch to filesystem
 			((num_patched++))
 		fi
 
 		# set dir/file permissions
-		chown $owner:$group $dest
-		chmod $perms $dest
+		chown $owner:$group $dest 2> /dev/null
+		chmod $perms $dest 2> /dev/null
 		
 	done < $MANIFEST
 
@@ -133,18 +150,48 @@ ApplyPatches() {
 		echo "no action taken. all files are intact" 
 	else
 		echo "$num_patched files patched."
+		echo -e "\nrevert changes with './patch restore'"
 	fi
 
 }
 
 Backup() {
-	echo "creating backup..."
-	echo "backup created."
+	file=$1
+	mkdir $BACKUP_DIR 2> /dev/null
+	echo "creating backup of $file"	 
+	cp --parents -r $file $BACKUP_DIR
 }
 
 Restore() {
-	echo "restoring from backup..."
-	echo "restore complete."
+	echo "restoring..."
+	num_restored=0
+	while read -r line
+	do
+		IFS=',' read -r -a array <<< $line
+                md5=${array[0]}
+		src=${array[1]}
+		dest=${array[2]}
+		owner=${array[3]}
+		group=${array[4]}
+		perms=${array[5]}
+
+		restoreFile=$BACKUP_DIR$dest
+		if [ -f $restoreFile ]; then
+			# Check if a restore is necessary
+        		backup_md5=`md5sum $restoreFile | cut -d ' ' -f 1`
+			if [ ! $backup_md5 == `md5sum $dest | cut -d ' ' -f 1` ]; then
+				echo "restoring $dest"
+				cp -f $restoreFile $dest
+				((num_restored++))
+			fi
+		fi
+
+	done < $MANIFEST
+	if [ $num_restored -gt 0 ]; then
+		echo -e "complete\n$num_restored file(s) restored."
+	else
+		echo "no action taken. restore was not required"
+	fi
 }
 
 
@@ -158,17 +205,22 @@ if [ $# == 1 ]; then
 	if [ `echo $1` == 'build' ]; then
 		Build
 	elif [ `echo $1` == 'restore' ]; then
-		Restore
+		while true; do
+    			read -p "Do you wish to undo all changes that were applied by the patch? " yn
+    			case $yn in
+        			[Yy]* ) Restore; break;;
+        			[Nn]* ) exit;;
+        			* ) echo "Please answer yes or no.";;
+    			esac
+		done
 	fi
 else
 	while true; do
-		echo "WARNING! THIS ACTION CANNOT BE UNDONE!"
-
     		read -p "Do you wish to run this patch? " yn
     		case $yn in
         		[Yy]* ) ApplyPatches; break;;
-        	[Nn]* ) exit;;
-        	* ) echo "Please answer yes or no.";;
+        		[Nn]* ) exit;;
+        		* ) echo "Please answer yes or no.";;
     		esac
 	done
 fi
